server:
  port: 8082

spring:
  application:
    name: order

  datasource:
    url: jdbc:mysql://47.106.198.5:3306/Spring_Cloud_Sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: yujun
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

